server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/Documents/Treinamento/Microservices/Labs/spring-cloud/lab1/spring-cloud-config-repo
#          uri: file://home/eduardo/Documents/Treinamento/spring-cloud/spring-cloud-lab1/spring-cloud-config-repo